# Discord2FA - A Minecraft Plugin to secure your Account with Discord!
# Developer: sieadev
# Contact Discord[@sieadev] GitHub[@sieadev] Email[Contact@siea.dev]

# ----------------------------- Data -----------------------------
# MYSQL or FILE
storage: "FILE"
fileAsFallback: true #This will use files if the database is not accessible

database:
  ip: ""
  name: ""

  user: ""
  password: ""

discord:
    token: ""
    guild: ""
    channel: "" # Link Message Channel
    role: "" # Empty for non

allowedCommands: ["/login"]    # Commands allowed before the Player is verified

# --------------------------- Messages ---------------------------
# Moved to ./Discord2FA/messages.yml