# Discord2FA - A Minecraft Plugin to secure your Account with Discord!
# Developer: sieadev
# Contact Discord[@sieadev] GitHub[@sieadev] Email[Contact@siea.dev]

database:
  ip: ""
  name: ""

  user: ""
  password: ""

discord:
    token: ""
    guild: ""
    channel: "" # Link Message Channel

messages:
  verify:
    title: "Verify Login"
    text: "Someone logged into your Account from a new Location(%ip%)"
    footer: "If this wasn't you, change your Password immediately!"
    VerifyButton: "Verify"
    DenyButton: "Deny"
  verifyDenied: "Verification denied!"
  verifySuccess: "You successfully verified your Account!"
  alreadyLinked: "Your Account is already linked!"
  link:
    title: "Link your Account!"
    text: "Want to make your Minecraft Account more secure? Link it with your Discord!"
    footer: "Click the Button below to link your Account!"
    linkButton: "Link"
  codeMessage: "Your Verification Code is: %code%"
  invalidCode: "&cInvalid Code!"
  linkSuccess: "&aYou successfully linked your Account"
  noCode: "&cYou must provide a Code!"
  verifyTitle: "Verify your Account!"
  alreadyLinking: "You already been send a Verification Code!"
  notLinked: "You are not linked!"
  unlinkSuccess: "You successfully unlinked your Account!"
  acceptMessage: "You accepted the Verification!"
  denyMessage: "You denied the Verification!"