#################################################################
# +-----------------------------------------------------------+ #
# |      Discord2FA - Easy Discord <-> Minecraft linking      | #
# |                  Made with <3 by sieadev                  | #
# +-----------------------------------------------------------+ #
#################################################################

# Contact Discord[@sieadev] GitHub[@sieadev] Email[Contact@siea.dev]

# ----------------------------- Lang -----------------------------
# Choose from EN,IT and DE | Something missing? You can always reach out to me and add your own!
language: en
playerSpecificTranslations: true

# ----------------------------- Data -----------------------------
# MYSQL or FILE
storage: "FILE"
fileAsFallback: true #This will use files if the database is not accessible

database:
  ip: ""
  name: ""

  user: ""
  password: ""

# -------------------------- DiscordBot --------------------------
discord:
    token: ""
    guild: ""
    channel: "" # Link Message Channel

# --------------------------- Settings ---------------------------
allowedCommands: ["/link"] # Commands allowed before the Player is verified
force-link: false # Force Users to Link their accounts